def deBruijn(Text,k):
    n = len(Text)
    adjList = dict()
    nodes = set()
    y = k - 1
    allKmers = []
    for i in range(n-y+1):
        sub = Text[i:i+y]
        nodes.add(sub)
    print(nodes)
    nodes = list(nodes)
    nodes.sort()
    for i in range(n-k+1):
        sub = Text[i:i+k]
        allKmers.append(sub)
    for j in nodes:
        dummy = []
        for i in allKmers:
            a = i[1:]
            a1 = i[:k-1]
            if j==a1:
                dummy.append(a)
        if j not in adjList:
            adjList[j] = dummy
    return adjList
    
text = "GTTTGGAGCCCGTACGATATCTTATAAAGAGGACATTCCCAGCGAGGACTAGGACCGAGTAAGTATGCTCGTCTTAGTCATCGACATGCAAGACTTGGCACTGATTATACCATGAAGCGCACGCCCGACGCCGGAGGCAATGTATACCGCATGCGACTAAAGCACCACTGCGTCGCAATGCCAGTGTGTGAGGACGTCACGCGCTGCACGATCAAATTCTTGCATCTGGTGTCCAGGGCCTCGCGCTCACCACTTACAGGTTAACCCGTCCAATATTTAAACTGATAGGCTAGTACGAGCCCTGGGATGTTGGTACGGATACTCGCAGTTTGGGCAGGATGCTTGGACTTTTGGTACACGTGTACATTGGCGTCTATCTCACAGTCGTATGTGAGATACGCAAGCTTTAGGGAGCCAGCCAGTCCGCTACCACCAACCTGAGCCTTCCGGTGTCTATAAATACACTCCAATTAGGCTGAGTGTCAATATACCACCTCATCGGCCACTCGTGATGAGGTTCCGCCAAGTCTATAGACAATATCGCCGGAGTTGGGCGACAGTAAACAGCGCGGGGCACGGCAGTGAATTGAAGATACTTCTAGTGGTAACAGACGTAGATCTCGATAAAATTCCTTATGACGTCGTCATCGGTAGTGCGACTGCGTTTCAACGTGGAGATGAGCGGCGATTGGGCTACGATCTGTAGTGCGAGCCATATTTTGTTCGGCCGCAGAGTGGTATAACGGAGGAGGTGTCACTGCTGATTTGAACAATTCTCTAACGTCAAAGTGACCGTTGTCCGTCAGCGCGGCAGTTGCGACTGTTAACCGGGCATAGTACAATAGCGTGGATGGTGGGGCCGGACGCGCCCACGCGTGAGTCTGCTAAGGTTGTCAAAGTACTAGCCGTTTTCGATGGAAGCTGAATGCGCGCCCTGAGGACGCTCGGCCAAGACAACCAGATCCCGCCGCGGAGCCCGTCCACCTAAGGTGCACCAGCATGCCCGGATTTACTTCCACATAACTTGGTATCGTCTAGAATCCTTAATCTGTATATACAGGCCTAGTATCCAACGAGCGCTCTAGTGAGAGTGTCACACTCAAGGTCCTGCGGGTGTCTCGTGTATAACGGAGGACCCATCATGATTCGGCGGCTCCATTAACTAAGAGGTTTTACGTAGCTTCCGGTGAGTTCGTATACTAAACTCCTGTCTTTTATTGGTAGCGTTCAAAACCAATCCTTCTGCCTGCCGATCGACTAAGGAGCAGCGGCCGCGGAAATCAGATAGAATCAAGTGCACGGTGTGCCTAATCGACACTTGCCCACTACGGCCACTCTAGCGTAGAAGCTAGGAGCTATCAGATTTCTAGCTATTGAGATATGTTGATGAGCGAGTCCAAGAATAATTGCTATCTCGAAACGAGGACACTGAGGGATCGGAGTGCAATAGGACTTAACATACGGTCCTAAGCACATCAAATGGTCATAAAGATAGATCAGGCATGGAGAACTAAAAGTATGATATTATAGGCCAGTAACTCAGATAGGCGAGTCTCGGAGAGATTAACCCTAACTGCCGTCTATACTAGATCCCTGGAATCCGGAATACGCTCGCACCTTTCACTAAGGAGCCCCGATCTCGAATTCACGCTCAATGGGCTCCTCACTCAGGTGGACCCCTCTAACCATCCCTCGTATCCGCAGGTGCAGGTGAATATCAGATGGTGACGTTCTTGATCGGCTCTGCTGCAGACCTTAGAGCGATTTCAACTTCCAAGCTGCGTGCAAGCCGCCCTGTCATACTACTAGCGGAGTGTTCTGGGTTTGCGCTATAGTTGCATACCGCTCATCGAAACACCCCGATGTCTGAGAGGCCAAGAAACTGACCGTTTATCTAATCTACGGTATCAACAATCAGCAAGACTTGTCTTTCAGGCACTGATTATTCGATGAGGTAATCGTCCTGGCTTATAGCCCTGCGCTGGGCCCTTTGATCGCAT"
k = 12
ans = deBruijn(text,k)
f=open('oal.txt','a')
for key, value in ans.items():
    if len(value) > 0:
        answer = key+ " -> "+ ",".join(value)
        f.write(answer)
        f.write("\n")
f.close()
    